[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'
<<<<<<< HEAD
gas_reports = ["EmegencyBrakeV2"]
=======
solc_version = '0.8.15'
rpc_endpoints = { mainnet = "${MAINNET_RPC}" }
>>>>>>> 080e181 (feat: begin safeApprove)
